PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX osi: <http://ontologies.geohive.ie/osi#>
PREFIX geo: <http://www.opengis.net/ont/geosparql#>
PREFIX geof: <http://www.opengis.net/def/function/geosparql/>
PREFIX sf: <http://www.opengis.net/ont/sf#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

PREFIX trail: <http://example.org/trail/>

# Find trails with given format in the current district.
#   Parameters:  format
#   Returns:     district, trailName

SELECT ?districtName ?trailName ?trailFormat
WHERE {
  ?district a osi:Municipal_District.
  ?district rdfs:label ?districtName.
  ?district geo:hasGeometry ?geom.
  ?geom geo:asWKT ?wkt.

  ?trail a trail:Trail.
  ?trail trail:name ?trailName.
  ?trail trail:startPoint ?spGeom.
  ?spGeom geo:asWKT ?trailStartPoint.
  ?trail trail:hasFormat ?trailFormat.
  ?trailFormat trail:value "%PARAM_0%"^^xsd:string

  # Get the district of the trail.
  FILTER(geof:sfWithin(?trailStartPoint, ?wkt)).

  # Remove duplicates that have the @en language tag
  FILTER ( LANG(?districtName) = "" && LANG(?trailName) = "").
}
